# Pequeño tutorial de Pytorch

En este notebook vamos a desarrollar algunos aspectos básicos de PyTorch para implementar modelos sencillos

In [1]:
import torch
import numpy as np

Al igual que en Numpy, donde tenemos un objeto fundamental (ndarray), pytorch tiene su propio objeto, que es muy similar a un array de Numpy, pero con mayores funcionalidades, fundamentalmente relacionadas al producto de tensores y calculo de gradientes (autograd).

In [2]:
a = torch.zeros(3,2) # Tensor de ceros
b = torch.randn(3,3,2) # tensor de numeros aleatorios
print(a)
print(b)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[[-0.1932, -1.3645],
         [-1.3809,  1.4023],
         [-1.3404, -0.9427]],

        [[-0.4223,  0.2423],
         [ 0.6098,  0.0603],
         [-1.0045, -0.1565]],

        [[-1.8231, -1.7659],
         [-1.2167,  0.0636],
         [-1.5977, -0.0681]]])


In [3]:
c = torch.tensor([[1,2],[3,4],[5,6]]) # tensor a partir de una lista
print(c)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [4]:
rng = np.random.default_rng()
a = rng.normal(size=(2,2,3))
b = torch.from_numpy(a)
print(b)    

tensor([[[-0.5991, -1.7046, -0.6497],
         [-1.0011, -0.4523,  0.7368]],

        [[-0.3121,  0.1646, -1.1698],
         [ 0.7263,  2.0821,  0.0850]]], dtype=torch.float64)


Las operaciones tipicas de numpy se pueden utilizar en pytorch: manejo de indices, operaciones aritmeticas

In [5]:
print(b)
b.shape

tensor([[[-0.5991, -1.7046, -0.6497],
         [-1.0011, -0.4523,  0.7368]],

        [[-0.3121,  0.1646, -1.1698],
         [ 0.7263,  2.0821,  0.0850]]], dtype=torch.float64)


torch.Size([2, 2, 3])

In [6]:
# En vez de reshape, se utiliza el metodo view

b.view(4,3)

tensor([[-0.5991, -1.7046, -0.6497],
        [-1.0011, -0.4523,  0.7368],
        [-0.3121,  0.1646, -1.1698],
        [ 0.7263,  2.0821,  0.0850]], dtype=torch.float64)

In [7]:
# al igual que en Numpy, -1 es un comodin para redimensionar
b.view(6,-1)

tensor([[-0.5991, -1.7046],
        [-0.6497, -1.0011],
        [-0.4523,  0.7368],
        [-0.3121,  0.1646],
        [-1.1698,  0.7263],
        [ 2.0821,  0.0850]], dtype=torch.float64)

In [8]:
b.view(-1)

tensor([-0.5991, -1.7046, -0.6497, -1.0011, -0.4523,  0.7368, -0.3121,  0.1646,
        -1.1698,  0.7263,  2.0821,  0.0850], dtype=torch.float64)

In [9]:
# Para hacer un cast de un tensor en un ndarray, basta con utilizar el metodo numpy()

b.numpy()

array([[[-0.59905006, -1.70464776, -0.64974363],
        [-1.00111894, -0.45233454,  0.73684236]],

       [[-0.31211146,  0.16459671, -1.16975174],
        [ 0.72630958,  2.08212998,  0.08497032]]])

## Autograd - Grafos computacionales y diferenciacion!

In [10]:
a = torch.tensor(1., requires_grad= True) # requires_grad significa que guarda y calcula el grafo computacional
b = torch.tensor(2.,requires_grad= True)

f = a + b  # Tensor con la suma

c = torch.tensor(3., requires_grad= True)

g = f*c


In [11]:
g.backward() # el metodo backward recorre el grafo hacia atras encontrando todas las derivadas

LAs derivadas se calculan llamando simplemente llamando al atributo grad

$$
\frac{dg}{da} = \frac{dg}{df}\frac{df}{da},\ \frac{dg}{db} = \frac{dg}{df}\frac{df}{db}, \frac{dg}{dc} = \frac{dg}{dc} 
$$
$$
\frac{dg}{da} = c \times 1,\ \frac{dg}{db} = c \times 1, \frac{dg}{dc} = f 
$$

In [12]:
print(a.grad, b.grad, c.grad)

tensor(3.) tensor(3.) tensor(3.)


## GPUS  - manejo

In [13]:
# Para saber si tenemos una GPU disponible
torch.cuda.is_available()

False

In [14]:
# En caso de tener una GPU disponible, basta con alojar los tensores en la GPU y operar con ellos
a = torch.randn(1000,1000).cuda() 

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [15]:
# una buena practica es definir una variable que identifique el tipo de procesador y utilice la gpu por defecto
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# y utilizar el device 
a = torch.tensor(1., requires_grad= True, device= device)