# La librería Numpy

Para crear un array de NumPy primero hay que importar la librería: 

In [1]:
import numpy as np # esto importa la librería precompilada en nuestro intérprete
                    # y le asigna un alias (np) para no escribir numpy cada vez

In [6]:
# Se pueden crear arrays de muchas maneras
# mediante funciones intrinsecas
forma = (3,3)
a= np.empty(forma) #crea un array empty (numeros proximos a cero)
a=np.zeros(forma) # crea un array de ceros
print('shape:',a.shape,'size:',a.size)
forma = (10)
a=np.ones(forma, dtype=np.float64) #crea un array de unos de tipo float64 (NumPy debe manejar cuidadosamente los tipos y la precision)
print(a)
a = np.arange(forma) #crea un array con numeros enteros consecutivos
print(a, a.dtype) # el atributo dtype nos dice el tipo de dato y los bytes utilizados en cada elemento

shape: (3, 3) size: 9
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9] int64


In [7]:
#a partir de una lista/tupla
a = [1,2,3,4,5,6]
print(type(a))
a = np.array(a)
print(type(a))
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


Los arrays de numpy admiten slicing al igual que las listas, pero además admiten masking. Masking refiere a la utilizacion de otros arrays como índices.

In [20]:
vec = np.arange(15)*10
idxs = np.array([2,4,6])
print('el vector',vec)
print('el vector con los indices idx', idxs, vec[idxs])
mask = vec >= 50  # esta operacion se aplicara elemento a elemento
print(mask, mask.shape, vec.shape) # mask tiene la misma forma que vec
print(vec[mask], vec[mask].shape) # aplicar la mascara devuelve los elementos con indice True

el vector [  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140]
el vector con los indices idx [2 4 6] [20 40 60]
[False False False False False  True  True  True  True  True  True  True
  True  True  True] (15,) (15,)
[ 50  60  70  80  90 100 110 120 130 140] (10,)


Los arrays de numpy tienen muchos métodos, aparte de las funciones externas que operan sobre ellos

In [8]:
print(a)
print(a.argmax()) #argumento (indice) donde esta el maximo
print(a.argmin()) #arg donde esta el minimo
print(a.argsort()) #indices ordenados en orden creciente de valores del array
b = np.ones(6)*3 # cuando se multiplica por un escalar, se multiplica a cada elemento
print(a.dot(b)) #producto interno
print(a.reshape((2,3))) #le cambia la forma y lo hace una matriz de shape = (2,3)
b=np.diag((1,1,1)) #construye una matriz diagonal con los numeros provistos
print(b)
a.reshape((2,3)).dot(b) #producto de matrices

[1 2 3 4 5 6]
5
0
[0 1 2 3 4 5]
63.0
[[1 2 3]
 [4 5 6]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


array([[1, 2, 3],
       [4, 5, 6]])

Numpy tiene muchas funciones matematicas que pueden aplicarse a arrays de manera natural

In [9]:
print(np.sin(np.pi), np.exp(1))
x = np.linspace(0,2*np.pi,20) # genera un array equiespaciado
y = np.sin(x)
display = np.vstack([x,y]) #me apila los arrays
print(display.T) #con la T mayuscula se transpone una matriz

1.2246467991473532e-16 2.718281828459045
[[ 0.00000000e+00  0.00000000e+00]
 [ 3.30693964e-01  3.24699469e-01]
 [ 6.61387927e-01  6.14212713e-01]
 [ 9.92081891e-01  8.37166478e-01]
 [ 1.32277585e+00  9.69400266e-01]
 [ 1.65346982e+00  9.96584493e-01]
 [ 1.98416378e+00  9.15773327e-01]
 [ 2.31485774e+00  7.35723911e-01]
 [ 2.64555171e+00  4.75947393e-01]
 [ 2.97624567e+00  1.64594590e-01]
 [ 3.30693964e+00 -1.64594590e-01]
 [ 3.63763360e+00 -4.75947393e-01]
 [ 3.96832756e+00 -7.35723911e-01]
 [ 4.29902153e+00 -9.15773327e-01]
 [ 4.62971549e+00 -9.96584493e-01]
 [ 4.96040945e+00 -9.69400266e-01]
 [ 5.29110342e+00 -8.37166478e-01]
 [ 5.62179738e+00 -6.14212713e-01]
 [ 5.95249134e+00 -3.24699469e-01]
 [ 6.28318531e+00 -2.44929360e-16]]


También hay muchas operaciones complejas relacionadas con estadísticas, como cálculos de matrices de correlación, desviaciones y varianzas, histogramas. Transformadas discretas de Fourier, cálculo de números pseudoaleatorios y un largo etc. 

Como ejemplo, creemos distribuciones aleatorias y veamos algunas de sus propiedades

In [11]:
g1 = np.random.default_rng() # creamos un objeto generador
n = 1000000 # vamos a generar distribuciones de un millon de numeros aleatorios
unif = g1.uniform(size=n) # distribucion uniforme
norm = g1.normal(size=n)
pois = g1.poisson(size=n)
expo = g1.exponential(size=n)

In [12]:
print('Medias, medianas y varianzas de cada distribucion')
print(f'Uniforme - media: {unif.mean()} - mediana: {np.median(unif)} - stdev: {unif.std()}')
print(f'Normal - media: {norm.mean()} - mediana: {np.median(norm)} - stdev: {norm.std()}')
print(f'Poisson - media: {pois.mean()} - mediana: {np.median(pois)} - stdev: {pois.std()}')
print(f'Exponencial - media: {expo.mean()} - mediana: {np.median(expo)} - stdev: {expo.std()}')

Medias, medianas y varianzas de cada distribucion
Uniforme - media: 0.5001702115968182 - mediana: 0.5000555421831345 - stdev: 0.28860728142320585
Normal - media: 0.00016001617178576104 - mediana: -0.00016181192681302573 - stdev: 1.000091930903227
Poisson - media: 0.998548 - mediana: 1.0 - stdev: 1.0002789069534557
Exponencial - media: 0.9990484511011648 - mediana: 0.6929883845291498 - stdev: 0.9989817138085245


In [13]:
# se pueden calcular histogramas
histo_unif, bins_unif = np.histogram(unif, range=(0,1),bins=10)  #los bins tienen n+1 elementos (devuelve los bordes)
#voy a hacer la funcion integrada de numpy para contrastar
histo_expo, bins_expo = np.histogram(expo, range=(0,1),bins=10)

print(bins_expo)
print(histo_unif)
print(histo_expo)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[ 99694  99897  99982 100047 100314 100191 100039  99739  99668 100429]
[95398 85699 78215 70172 64006 57996 51949 47554 43061 38464]
